swagger: "2.0"
info:
  version: "1.0.0"
  title: "Resume Ready API"
  description: "API documentation for Resume Ready application."

host: "localhost:5000"
basePath: "/"
schemes:
  - http

paths:
  /auth/login:
    get:
      tags:
        - Auth
      summary: "Log in using Auth0."
      responses:
        302:
          description: "Redirects to the Auth0 login page."

  /auth/callback:
    get:
      tags:
        - Auth
      summary: "Callback from Auth0 after login."
      responses:
        200:
          description: "Returns the user's information and tokens."
          schema:
            type: object
            properties:
              message:
                type: string
              accessToken:
                type: string
              idToken:
                type: string
              user:
                type: object
                properties:
                  sub:
                    type: string
                  email:
                    type: string
                  firstName:
                    type: string
                  lastName:
                    type: string

  /user/upload-pdf:
    post:
      tags:
        - User
      summary: "Upload a resume as a PDF."
      consumes:
        - multipart/form-data
      parameters:
        - in: formData
          name: file
          type: file
          required: true
          description: "PDF file to upload."
      responses:
        200:
          description: "Resume uploaded successfully."
          schema:
            type: object
            properties:
              message:
                type: string
              resumeUrl:
                type: string
        400:
          description: "Invalid input or missing file."
        500:
          description: "Error occurred during upload."

  /application/resume-feedback:
    post:
      tags:
        - Application
      summary: "Generate resume feedback."
      parameters:
        - in: body
          name: body
          required: true
          schema:
            type: object
            properties:
              userResume:
                type: string
                description: "User's resume content."
              jobDescription:
                type: string
                description: "Job description for the application."
      responses:
        200:
          description: "Resume feedback generated successfully."
          schema:
            type: object
            properties:
              feedback:
                type: object

  /application/process-application:
    post:
      tags:
        - Application
      summary: "Process the user's resume and job description."
      parameters:
        - in: body
          name: body
          required: true
          schema:
            type: object
            properties:
              userResume:
                type: string
                description: "User's resume content."
              jobDescription:
                type: string
                description: "Job description for the application."
              questionType:
                type: string
                default: Technical
                description: "Type of questions to generate."
              numQuestions:
                type: integer
                default: 3
                description: "Number of questions to generate."
      responses:
        200:
          description: "Application processed successfully."
          schema:
            type: object
            properties:
              message:
                type: string
              application:
                type: object
        400:
          description: "Missing required fields."
        500:
          description: "Error occurred during processing."
